/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_gnu_p7zip_Andro7za */

#ifndef _Included_net_gnu_p7zip_Andro7za
#define _Included_net_gnu_p7zip_Andro7za
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_net_gnu_p7zip_Andro7za_a7zaCommandAll
		(JNIEnv *env, jobject thisObj, jobjectArray inJNIArray);
		
JNIEXPORT jstring Java_net_gnu_p7zip_Andro7za_stringFromJNI(JNIEnv* env, jobject thiz, 
													jstring jOutfile, jstring jInfile);

JNIEXPORT void Java_net_gnu_p7zip_Andro7za_closeStreamJNI(JNIEnv* env, jobject thiz);

/*
 * Class:     net_gnu_p7zip_Andro7za
 * Method:    a7za_command
 * Signature: ()I
 */
//JNIEXPORT jint JNICALL Java_net_gnu_p7zip_Andro7za_a7zaCommand(JNIEnv *env, jobject obj, 
//		jstring _command, 
//		jstring _pathArchive,
//		jstring _type,
//		jstring _password,
//		jstring _outputDirOrCompressionLevel,
//		jstring _exclude,
//		jstring _fList4CompressOrExtract);
//
//JNIEXPORT jint JNICALL Java_net_gnu_p7zip_Andro7za_a7zaCommand2(
//		JNIEnv *env, jobject obj, 
//		jstring _command, 
//		jstring _pathArchive,
//		jstring _type,
//		jstring _password,
//		jstring _outputDirOrCompressionLevel,
//		jstring _1,
//		jstring _2,
//		jstring _3,
//		jstring _4,
//		jstring _5,
//		jstring _6,
//		jstring _7,
//		jstring _8,
//		jstring _9,
//		jstring _10,
//		jstring _11,
//		jstring _12,
//		jstring _fList4CompressOrExtract
//		);
		
#ifdef __cplusplus
}
#endif
#endif
